### ISSUE TITLE
Google tasks webapp does not work

### ISSUE THREAD

**Issue by ghost** [Mossop/WebAppTabs#53] opened 2012-10-25 13:41 UTC
Hey!

I added google tasks webapp but nothing appears.
both of the following links worked in Firefox but not in WebApp Tabs.

https://mail.google.com/tasks/canvas
https://mail.google.com/tasks/ig

Is there something to do about this?
thanks

**Comment by Mossop** [comment] 2012-10-25 16:41
This is a duplicate of issue #46, I really must release the updated version.

**Closed as completed by Mossop** 2012-10-25 16:41 UTC

**Comment by bets** [comment] 2012-10-25 16:43
I'd like that :)
